### ISSUE TITLE
 does not specify a Swift version and none of the targets !

### ISSUE THREAD

**Issue by caojianfeng** [flutter-moum/flutter_open_appstore#19]
I import the open_appstore like this:
```
...
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # https://github.com/CaiJingLong/flutter_ijkplayer
  flutter_ijkplayer: 0.3.3

  # https://github.com/letsar/flutter_sticky_header
  flutter_sticky_header: 0.4.0

  # https://github.com/flutter-moum/flutter_open_appstore
  open_appstore: 1.0.2
...

```
BUT receive this:
`open_appstore` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION`

my project using object_c

soukenbons-iMac:msk_s caojianfeng$ flutter run
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running pod install...                                              6.7s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A open_appstore
      R url_launcher
      - Flutter
      - flutter_ijkplayer

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `flutter_ijkplayer` from `.symlinks/plugins/flutter_ijkplayer/ios`
    -> Fetching podspec for `open_appstore` from `.symlinks/plugins/open_appstore/ios`

    Resolving dependencies of `Podfile`

    Comparing resolved specification to the sandbox manifest
      A Flutter
      A FlutterIJK
      A flutter_ijkplayer
      A open_appstore

    Downloading dependencies

    -> Installing Flutter (1.0.0)

    -> Installing FlutterIJK (0.1.0)
      > Copying FlutterIJK from `/Users/caojianfeng/Library/Caches/CocoaPods/Pods/Release/FlutterIJK/0.1.0-68b00` to `Pods/FlutterIJK`

    -> Installing flutter_ijkplayer (0.0.1)

    -> Installing open_appstore (0.0.1)
      - Running pre install hooks
    [!] Unable to determine Swift version for the following pods:

    - `open_appstore` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION`
    attribute in at least one of the targets that integrate this pod.

    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/target_validator.rb:122:in `verify_swift_pods_swift_version'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/target_validator.rb:37:in `validate!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:578:in `validate_targets'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:158:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/command/install.rb:51:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See
    `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone 11 Pro Max.
soukenbons-iMac:msk_s caojianfeng$
