### ISSUE TITLE
null-safetey

### ISSUE THREAD

**Issue by Armoured-Door-Studio** [flutter-moum/flutter_open_appstore#28]
Do you plan to upgrade this package to the new [null-saftey](https://flutter.dev/docs/null-safety)?

**Comment by kimmy-wang** [comment]
```
open_appstore:
    git:
      url: https://github.com/ChangJoo-Park/flutter_open_appstore.git
      ref: master
```
